// GENERATED by tincture-codegen.mjs from registry.json — do not edit.

export type SemanticToken =
  | 'ink'
  | 'ink-soft'
  | 'ink-muted'
  | 'bg'
  | 'bg-card'
  | 'bg-elev'
  | 'accent'
  | 'accent-fg'
  | 'accent-warm'
  | 'border'
  | 'border-soft';

export type Flavor =
  | 'cool'
  | 'warm'
  | 'ember';

export type Surface = 'light' | 'dark';

export type ComponentName =
  | 'Hero'
  | 'Pricing'
  | 'ReviewSpotlight';

export type ColorMode = 'light' | 'dark';

export interface TokenManifest {
  type: 'color' | 'space' | 'radius' | 'shadow';
  lightValue: string;
  darkValue: string;
  doc: string;
  role: string | null;
  contrastPair: string | null;
  legacy: string[];
}
