#!/usr/bin/env node
/**
 * Tincture v0.2 — multi-axis codegen.
 *
 * Reads a v0.2 registry (validated via src/schema.mjs) and emits:
 *   - <out>/foundation.css   — cascade rules per axis-cell, NO light-dark()
 *   - <out>/manifest.json    — flat shape: { tokens[id]: { defaultValue, cells[] } }
 *   - <out>/tokens.d.ts      — TS union of token IDs
 *
 * Output is deterministic and byte-identical across runs (idempotent).
 *
 * Cascade strategy (cycle 21 decision 8):
 *   - :root gets default value
 *   - [data-<axis>=<value>] selectors override per single-axis cell
 *   - Compound selectors [data-axis1=v1][data-axis2=v2] stack specificity
 *   - Order of emission: default → 1-axis → 2-axis → 3-axis (ascending),
 *     so higher-specificity rules come later and win on cascade ties
 *
 * Run:
 *   node src/cli/codegen-v2.mjs --registry path/to/registry.json --out path/to/_generated/
 *   node src/cli/codegen-v2.mjs (defaults to ../registry.example.json + ../_generated/)
 *
 * Cycle 22.
 */

import { readFileSync, writeFileSync, existsSync, mkdirSync, readdirSync, unlinkSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve, basename } from 'node:path';
import { validateRegistry, AXES } from '../schema.mjs';

const __dirname = dirname(fileURLToPath(import.meta.url));

// ── arg parsing ─────────────────────────────────────────────────────
function arg(name, fallback) {
  const i = process.argv.indexOf(name);
  return i >= 0 ? process.argv[i + 1] : fallback;
}

const REGISTRY_PATH = resolve(arg('--registry', resolve(__dirname, '../registry.v02-example.json')));
const OUT_DIR = resolve(arg('--out', resolve(__dirname, '../_generated-v2')));
const QUIET = process.argv.includes('--quiet');

// ── load + validate ─────────────────────────────────────────────────
const reg = JSON.parse(readFileSync(REGISTRY_PATH, 'utf8'));
const result = validateRegistry(reg);
if (!result.ok) {
  console.error(`✗ registry validation failed:`);
  for (const e of result.errors) console.error(`  - ${e}`);
  process.exit(1);
}

// ── helpers ─────────────────────────────────────────────────────────

/** Parse a cell key into ordered [axis, value] pairs (or [] for default). */
function parseCell(key) {
  if (key === 'default') return [];
  return key.split(',').map(p => p.split('='));
}

/** Selector for a cell key. 'default' → ':root'; axes → '[data-X=Y][data-W=Z]'. */
function cellSelector(key) {
  if (key === 'default') return ':root';
  return parseCell(key).map(([a, v]) => `[data-${a}="${v}"]`).join('');
}

/** Sort cell keys: default first, then by axis count ascending, then alpha. */
function sortCellKeys(keys) {
  return [...keys].sort((a, b) => {
    if (a === 'default') return -1;
    if (b === 'default') return 1;
    const ca = a.split(',').length;
    const cb = b.split(',').length;
    if (ca !== cb) return ca - cb;
    return a.localeCompare(b);
  });
}

// ── emit foundation.css ──────────────────────────────────────────────
function emitFoundationCSS() {
  const lines = [];
  lines.push(`/* GENERATED by tincture/codegen-v2.mjs — do not edit by hand. */`);
  lines.push(`/* Registry: ${reg.name || '(unnamed)'} v${reg.version} */`);
  lines.push(`/* Run: pnpm tincture:codegen */`);
  lines.push(``);

  // Auto-fill axis-value reset cells.
  //
  // Why: cascade composition is broken if a token declares axis=X with
  // only SOME values present. E.g. token `--ink` has axes:['surface'] and
  // values { default: '#1A1612', 'surface=dark': '#fff' }. The output:
  //   :root                     { --ink: #1A1612 }
  //   [data-surface="dark"]     { --ink: #fff }
  //   [data-surface="light"]    { /* empty — NO --ink override */ }
  // Now if a descendant of [data-surface="dark"] declares
  // [data-surface="light"], it inherits --ink: #fff (from the dark
  // ancestor) instead of resetting to #1A1612. Bug.
  //
  // Fix: for every token T with axes A, for every value V of every axis
  // in A, ensure T has a value at V. Auto-fill missing values from the
  // default (or the most-specific declared compound cell). The reset
  // value re-declares default explicitly, so a sibling [data-X=other-V]
  // resets correctly via cascade.
  const AXIS_VALUES_RUNTIME = {
    surface: ['light', 'dark'],
    flavor: ['cool', 'warm', 'ember'],
    tone: ['feature', 'prose', 'surface', 'brand-band'],
    elevation: ['flat', 'lifted', 'dramatic'],
  };

  function autoFillToken(tok) {
    if (tok.axes.length === 0) return tok.values; // no axes → no fill
    const filled = { ...tok.values };
    // For each axis the token responds to, ensure every axis-value is
    // either explicitly declared OR inherits the default. We add a
    // single-axis cell for the default value of each axis-value that
    // doesn't already exist as a single-axis cell.
    for (const axis of tok.axes) {
      for (const value of AXIS_VALUES_RUNTIME[axis] || []) {
        const cellKey = `${axis}=${value}`;
        if (filled[cellKey] === undefined) {
          filled[cellKey] = filled.default;
        }
      }
    }
    return filled;
  }

  // Collect all (cellKey → [{tokenId, value}]) so we emit one rule per
  // unique cellKey (group all tokens for that cell into one CSS block).
  // This produces denser output AND keeps cascade specificity uniform.
  const cellGroups = new Map(); // cellKey → [{ id, value, doc }]
  for (const [tokenId, tok] of Object.entries(reg.tokens)) {
    const filled = autoFillToken(tok);
    for (const [cellKey, value] of Object.entries(filled)) {
      if (!cellGroups.has(cellKey)) cellGroups.set(cellKey, []);
      cellGroups.get(cellKey).push({ id: tokenId, value, doc: tok.doc });
    }
  }

  // Emit in the canonical order
  for (const cellKey of sortCellKeys([...cellGroups.keys()])) {
    const tokens = cellGroups.get(cellKey);
    const selector = cellSelector(cellKey);

    if (cellKey === 'default') {
      lines.push(`/* :root — default values for every token. */`);
    } else {
      lines.push(`/* ${cellKey} */`);
    }
    lines.push(`${selector} {`);

    // Special: default cell ALSO gets color-scheme from surface axis
    // (so :root has color-scheme: light by default, [data-surface=dark]
    //  has color-scheme: dark, [data-surface=light] has color-scheme: light)
    if (cellKey === 'default') {
      lines.push(`  color-scheme: light;`);
    } else if (cellKey === 'surface=dark') {
      lines.push(`  color-scheme: dark;`);
    } else if (cellKey === 'surface=light') {
      lines.push(`  color-scheme: light;`);
    }

    // Sort token IDs alphabetically for determinism
    const sortedTokens = [...tokens].sort((a, b) => a.id.localeCompare(b.id));
    for (const t of sortedTokens) {
      if (cellKey === 'default' && t.doc) {
        lines.push(`  /* ${t.doc} */`);
      }
      lines.push(`  --${t.id}: ${t.value};`);
    }

    // Sentinel only on :root
    if (cellKey === 'default') {
      lines.push(``);
      lines.push(`  --tincture-foundation-version: "${reg.version}";`);
    }

    lines.push(`}`);
    lines.push(``);
  }

  return lines.join('\n');
}

// ── emit manifest.json ───────────────────────────────────────────────
function emitManifest() {
  // Flat shape designed for studio designer + manifest-loader consumption.
  const tokens = {};
  for (const [tokenId, tok] of Object.entries(reg.tokens).sort(([a], [b]) => a.localeCompare(b))) {
    tokens[tokenId] = {
      kind: tok.kind,
      axes: tok.axes,
      locked: !!tok.locked,
      doc: tok.doc || '',
      defaultValue: tok.values.default,
      cells: sortCellKeys(Object.keys(tok.values)).map(key => ({
        cell: key,
        value: tok.values[key],
        selector: cellSelector(key),
      })),
    };
  }
  return JSON.stringify({
    schemaVersion: '2.0',
    registry: {
      version: reg.version,
      name: reg.name || null,
      doc: reg.doc || null,
    },
    axes: AXES,
    tokens,
  }, null, 2) + '\n';
}

// ── emit tokens.d.ts ─────────────────────────────────────────────────
function emitTokenTypes() {
  const ids = Object.keys(reg.tokens).sort();
  const union = ids.length === 0 ? 'never' : ids.map(id => JSON.stringify(id)).join(' | ');
  return [
    `// GENERATED by tincture/codegen-v2.mjs — do not edit by hand.`,
    `// Registry: ${reg.name || '(unnamed)'} v${reg.version}`,
    ``,
    `/** Union of every token ID in the registry. */`,
    `export type TokenId = ${union};`,
    ``,
    `/** All token IDs as a tuple (use \`as const\` for inference). */`,
    `export const TOKEN_IDS = [${ids.map(id => JSON.stringify(id)).join(', ')}] as const;`,
    ``,
  ].join('\n');
}

// ── write artifacts ──────────────────────────────────────────────────
function writeIfChanged(path, content) {
  let prev = '';
  try { prev = readFileSync(path, 'utf8'); } catch {}
  if (prev === content) {
    if (!QUIET) console.log(`  unchanged  ${basename(path)}`);
    return false;
  }
  if (!existsSync(dirname(path))) mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, content);
  if (!QUIET) console.log(`  written    ${basename(path)} (${content.length} bytes)`);
  return true;
}

const foundation = emitFoundationCSS();
const manifest = emitManifest();
const tokenTypes = emitTokenTypes();

let changed = 0;
if (writeIfChanged(resolve(OUT_DIR, 'foundation.css'), foundation)) changed++;
if (writeIfChanged(resolve(OUT_DIR, 'manifest.json'), manifest)) changed++;
if (writeIfChanged(resolve(OUT_DIR, 'tokens.d.ts'), tokenTypes)) changed++;

if (!QUIET) console.log(`\n${changed} file(s) changed.`);
process.exit(0);
