#!/usr/bin/env node
/**
 * tincture-codegen.mjs — cycle 5.
 *
 * Reads tincture/registry.json and emits 4 derivative files:
 *   - tincture/_generated/foundation.css   (light-dark() core token block)
 *   - tincture/_generated/flavors.css      (flavor override blocks)
 *   - tincture/_generated/manifest.json    (flat shape for designer studio)
 *   - tincture/_generated/tokens.d.ts      (TS union types)
 *
 * Pipeline:
 *   1. Run tincture-validate-registry.mjs (fail-fast on drift)
 *   2. Read registry.json
 *   3. Resolve primitive references
 *   4. Emit each artifact deterministically
 *
 * Idempotent: re-running produces byte-identical output. CI can verify.
 */

import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'node:fs';
import { execSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, '..');
const TINCTURE = resolve(ROOT, 'src/tenants/arzadon/tincture');
const GENERATED = resolve(TINCTURE, '_generated');
const REGISTRY = resolve(TINCTURE, 'registry.json');

const dry = process.argv.includes('--dry');
const skipValidate = process.argv.includes('--skip-validate');

// 1. Run validator
if (!skipValidate) {
  try {
    execSync(`node ${resolve(__dirname, 'tincture-validate-registry.mjs')}`, { cwd: ROOT, stdio: 'inherit' });
  } catch {
    console.error('\nx codegen aborted: registry validation failed.');
    process.exit(1);
  }
}

// 2. Load registry
const reg = JSON.parse(readFileSync(REGISTRY, 'utf8'));

// 3. Resolve primitive refs
function resolveRef(value, prim) {
  if (typeof value !== 'string') return value;
  const m = value.match(/^\{primitives\.color\.([^}]+)\}$/);
  if (!m) return value;
  return prim?.color?.[m[1]]?.value ?? value;
}

// 4. Emit foundation.css
function emitFoundation() {
  const lines = [];
  lines.push(`/* GENERATED by tincture-codegen.mjs from registry.json — do not edit. */`);
  lines.push(`/* Run: pnpm tincture:codegen */`);
  lines.push(``);
  lines.push(`:root {`);
  lines.push(`  /* Default scheme: light. Components inside [data-surface=dark] flip. */`);
  lines.push(`  color-scheme: light dark;`);
  lines.push(`}`);
  lines.push(``);
  lines.push(`/* Surface declarations */`);
  lines.push(`[data-surface="dark"]  { color-scheme: dark; }`);
  lines.push(`[data-surface="light"] { color-scheme: light; }`);
  lines.push(``);
  lines.push(`:root {`);
  for (const [id, tok] of Object.entries(reg.semantic)) {
    const light = resolveRef(tok.lightValue, reg.primitives);
    const dark = resolveRef(tok.darkValue, reg.primitives);
    const doc = tok.doc ? `  /* ${tok.doc} */\n` : '';
    lines.push(`${doc}  --${id}: light-dark(${light}, ${dark});`);
  }
  lines.push(``);
  lines.push(`  --tincture-foundation-version: "${reg.version}";`);
  lines.push(`}`);
  lines.push('');
  return lines.join('\n');
}

// 5. Emit flavors.css
function emitFlavors() {
  const lines = [];
  lines.push(`/* GENERATED by tincture-codegen.mjs from registry.json — do not edit. */`);
  lines.push(``);
  for (const [name, flavor] of Object.entries(reg.flavors)) {
    lines.push(`/* ${name} — ${flavor.doc ?? ''} */`);
    lines.push(`[data-flavor="${name}"] {`);
    if (Object.keys(flavor.overrides ?? {}).length === 0) {
      lines.push(`  /* (no overrides — foundation values represent ${name}) */`);
    } else {
      for (const [tokId, vals] of Object.entries(flavor.overrides)) {
        const light = vals.lightValue ? resolveRef(vals.lightValue, reg.primitives) : null;
        const dark = vals.darkValue ? resolveRef(vals.darkValue, reg.primitives) : null;
        if (light && dark) {
          lines.push(`  --${tokId}: light-dark(${light}, ${dark});`);
        }
      }
    }
    lines.push(`}`);
    lines.push(``);
  }
  return lines.join('\n');
}

// 6. Emit manifest.json (flat shape for studio)
function emitManifest() {
  const tokens = {};
  for (const [id, tok] of Object.entries(reg.semantic)) {
    tokens[id] = {
      type: tok.type,
      lightValue: resolveRef(tok.lightValue, reg.primitives),
      darkValue: resolveRef(tok.darkValue, reg.primitives),
      doc: tok.doc ?? '',
      role: tok.role ?? null,
      contrastPair: tok.contrastPair ?? null,
      legacy: tok.legacy ?? [],
    };
  }
  const flavors = {};
  for (const [name, f] of Object.entries(reg.flavors)) {
    flavors[name] = {
      doc: f.doc ?? '',
      overrides: Object.fromEntries(
        Object.entries(f.overrides ?? {}).map(([k, v]) => [
          k,
          {
            lightValue: v.lightValue ? resolveRef(v.lightValue, reg.primitives) : null,
            darkValue: v.darkValue ? resolveRef(v.darkValue, reg.primitives) : null,
          },
        ]),
      ),
    };
  }
  return JSON.stringify(
    {
      version: reg.version,
      generated: '2026-04-30',
      axes: reg.axes,
      tokens,
      flavors,
      components: reg.components ?? {},
    },
    null,
    2,
  ) + '\n';
}

// 7. Emit tokens.d.ts
function emitTypes() {
  const ids = Object.keys(reg.semantic).map((id) => `  | '${id}'`).join('\n');
  const compIds = Object.keys(reg.components ?? {}).map((id) => `  | '${id}'`).join('\n');
  const flavorIds = Object.keys(reg.flavors).map((id) => `  | '${id}'`).join('\n');
  return `// GENERATED by tincture-codegen.mjs from registry.json — do not edit.

export type SemanticToken =
${ids};

export type Flavor =
${flavorIds};

export type Surface = 'light' | 'dark';

export type ComponentName =
${compIds};

export type ColorMode = 'light' | 'dark';

export interface TokenManifest {
  type: 'color' | 'space' | 'radius' | 'shadow';
  lightValue: string;
  darkValue: string;
  doc: string;
  role: string | null;
  contrastPair: string | null;
  legacy: string[];
}
`;
}

// 8. Write artifacts
const artifacts = [
  { path: 'foundation.css', content: emitFoundation() },
  { path: 'flavors.css',    content: emitFlavors() },
  { path: 'manifest.json',  content: emitManifest() },
  { path: 'tokens.d.ts',    content: emitTypes() },
];

if (!existsSync(GENERATED)) {
  if (!dry) mkdirSync(GENERATED, { recursive: true });
}

const written = [];
for (const { path, content } of artifacts) {
  const full = resolve(GENERATED, path);
  const existing = existsSync(full) ? readFileSync(full, 'utf8') : null;
  if (existing === content) {
    written.push({ path, status: 'unchanged' });
    continue;
  }
  if (!dry) writeFileSync(full, content, 'utf8');
  written.push({ path, status: existing === null ? 'created' : 'updated' });
}

console.log('\ntincture-codegen — cycle 5');
console.log(`mode: ${dry ? 'dry-run' : 'apply'}`);
for (const w of written) console.log(`  ${w.status.padEnd(10)} ${w.path}`);
console.log('');
const changed = written.filter((w) => w.status !== 'unchanged').length;
console.log(`  ${changed} file(s) ${dry ? 'would change' : 'changed'}.`);
