#!/usr/bin/env node
/**
 * tincture-foundation.mjs — Phase 0 of the Tincture substrate.
 *
 * Creates <tinctureDir>/foundation.css with the
 * light-dark() core token block, adds an @import at the top of
 * globals.css, and annotates data-tone="feature" surfaces with
 * data-surface="dark" so light-dark() resolves correctly on those
 * surfaces even when the parent theme is light/grey.
 *
 * Surface luminance is a separate concept from theme:
 *   - Theme = which palette family (cool slate / warm parchment / ember)
 *   - Surface = is THIS subtree light-on-dark or dark-on-light?
 *
 * The browser's `color-scheme` CSS property + `light-dark()` function
 * pair to give every token a 2-state definition that auto-resolves
 * based on the closest ancestor that sets color-scheme.
 *
 * Visual no-op: the light-dark pairs are chosen so each token resolves
 * to the SAME value the existing per-theme block already produces.
 *
 * Idempotent: re-running on a clean tree is a no-op (the @import is
 * inserted only if not already present; data-surface annotations are
 * skipped if already present).
 *
 * Usage:
 *   node scripts/tincture-foundation.mjs            # apply
 *   node scripts/tincture-foundation.mjs --dry      # report only
 *   node scripts/tincture-foundation.mjs --check    # exit 1 if changes pending
 *
 * See: .soma/plans/tincture-2026-04-30/PLAN.md
 */

import { readFileSync, writeFileSync, existsSync, mkdirSync, readdirSync, statSync } from 'node:fs';
import { resolve, join } from 'node:path';
import { TINCTURE_DIR, GLOBALS_PATH, COMPONENTS_DIR, PAGES_DIR } from './_resolve-config.mjs';

const FOUNDATION_PATH = join(TINCTURE_DIR, 'foundation.css');

const dry = process.argv.includes('--dry');
const checkMode = process.argv.includes('--check');

// ─── Foundation CSS content ─────────────────────────────────────────────
const FOUNDATION_CSS = `/* ─────────────────────────────────────────────────────────────────────────
   tincture/foundation.css — Phase 0 of the Tincture substrate.

   Each token here is defined with light-dark(LIGHT_VALUE, DARK_VALUE).
   The browser resolves to LIGHT_VALUE or DARK_VALUE based on the closest
   ancestor's \`color-scheme\` declaration.

   Why: surface luminance is the real concept. A button on a dark surface
   needs light ink; on a light surface, dark ink. With per-theme blocks
   we had to maintain that mapping by hand and were missing it (orphan
   text-on-bg bugs). With light-dark() we declare the pair ONCE; the
   surface decides which side wins.

   Pair this with [data-surface] annotations on subtrees that flip
   luminance vs the parent theme (e.g. dark feature sections embedded
   inside a light page).

   Generated by scripts/tincture-init.mjs.
   \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500 */

:root {
  /* Default scheme: light. Components inside [data-surface=dark] flip. */
  color-scheme: light dark;
}

/* ── Surface declarations ──
   data-surface=dark : flip color-scheme to dark, regardless of [data-theme=*]
   data-surface=light : force color-scheme back to light (rare; nested override) */
[data-surface="dark"]  { color-scheme: dark; }
[data-surface="light"] { color-scheme: light; }

/* ── Core tokens (pair = light value, dark value) ──
   These resolve based on the closest ancestor with a color-scheme
   declaration. Values match what existing [data-theme=*] blocks
   produced, so this is a visual no-op for components that migrate. */

:root {
  /* Ink */
  --ink:        light-dark(#1A1612, #FFFFFF);
  --ink-soft:   light-dark(#4A4540, #B8B8C4);   /* secondary text */
  --ink-muted:  light-dark(#6A655E, #8E91A3);   /* tertiary / metadata */

  /* Surface backgrounds */
  --bg:         light-dark(#F7F4F0, #12151C);
  --bg-card:    light-dark(#FFFFFF, #1A1E28);
  --bg-elev:    light-dark(#EFEAE3, #242A36);

  /* Accent (saturated red — surface-aware) */
  --accent:        light-dark(#C41E3A, #E82E11);
  --accent-fg:     light-dark(#FFFFFF, #FFFFFF);
  --accent-warm:   light-dark(#C41E3A, #E82E11);   /* same as accent for now; flavor layer can shift */
  --accent-warm-fg: light-dark(#FFFFFF, #FFFFFF);

  /* Borders + shadows (alpha-tinted accent for warmth) */
  --border:        light-dark(rgba(26, 22, 18, 0.12), rgba(232, 46, 17, 0.18));
  --border-soft:   light-dark(rgba(26, 22, 18, 0.06), rgba(232, 46, 17, 0.10));

  /* Sentinel: never edit this in a mood preset \u2014 used to detect
     whether tincture/foundation.css was successfully imported. */
  --tincture-foundation-version: "0.1.0";
}

/* ── Sanity tests for during migration ──
   Pages can opt in to verify their surface declarations work:

     <body class="tincture-debug">
       \u2026
     </body>

   With this class on the root, each [data-surface] block gets a 2px
   outline so you can see at a glance which subtrees are flipping. */
.tincture-debug [data-surface="dark"]  { outline: 2px dashed #00ff88; }
.tincture-debug [data-surface="light"] { outline: 2px dashed #00aaff; }
`;

// ─── Files that need data-surface="dark" annotations ───────────────────
//
// Scan components + pages dirs for any file containing data-tone="feature".
// Add data-surface="dark" alongside (idempotent — skips if already present).
//
// Re-run safe: regex requires the absence of data-surface= already.

function walk(dir, exts = ['.tsx', '.ts'], skip = ['node_modules', '.next', '.git', 'dist', '__tests__', '_generated', '_archive']) {
  if (!existsSync(dir)) return [];
  const out = [];
  for (const name of readdirSync(dir)) {
    if (skip.includes(name)) continue;
    const p = join(dir, name);
    const st = statSync(p);
    if (st.isDirectory()) out.push(...walk(p, exts, skip));
    else if (exts.some((e) => p.endsWith(e))) out.push(p);
  }
  return out;
}

const CWD = process.cwd();
const scanDirs = [COMPONENTS_DIR, PAGES_DIR].filter(Boolean);
const SURFACE_PATCHES = scanDirs.flatMap(walk)
  .filter((p, i, arr) => arr.indexOf(p) === i) // dedupe
  .filter((p) => readFileSync(p, 'utf8').includes('data-tone="feature"'))
  .map((p) => ({ file: p, note: p.slice(CWD.length + 1) }));

// Idempotent annotator: matches data-tone="feature" not preceded by data-surface
// on the same element opening tag. Handles multi-line JSX attribute blocks
// (the /s flag lets . match newlines).
function annotateDataSurface(content) {
  // Note: no \b after "feature" — \b doesn't fire between '"' and whitespace
  // (both non-word chars). [\s\S]*? lets us span multi-line JSX attribute blocks.
  const re = /<(\w+)[\s\S]*?\bdata-tone="feature"[\s\S]*?>/g;
  let touched = 0;
  const next = content.replace(re, (full, tag, before, after) => {
    if (full.includes('data-surface=')) return full;
    touched++;
    // Replace just the data-tone attribute, preserving surrounding whitespace.
    return full.replace(/data-tone="feature"/, 'data-surface="dark" data-tone="feature"');
  });
  return { next, touched };
}

// ─── Engine ─────────────────────────────────────────────────────────────

let actions = [];

// 1. Ensure tincture dir exists
if (!existsSync(TINCTURE_DIR)) {
  if (!dry && !checkMode) mkdirSync(TINCTURE_DIR, { recursive: true });
  actions.push({ kind: 'mkdir', path: TINCTURE_DIR });
}

// 2. Write foundation.css if missing or stale
const foundationExists = existsSync(FOUNDATION_PATH);
const foundationStale = foundationExists && readFileSync(FOUNDATION_PATH, 'utf8') !== FOUNDATION_CSS;
if (!foundationExists || foundationStale) {
  if (!dry && !checkMode) writeFileSync(FOUNDATION_PATH, FOUNDATION_CSS, 'utf8');
  actions.push({ kind: foundationExists ? 'update' : 'create', path: FOUNDATION_PATH });
}

// 3. Insert @import in globals.css if not already present
const globals = readFileSync(GLOBALS_PATH, 'utf8');
const importLine = `@import "./tincture/foundation.css";\n`;
if (!globals.includes('tincture/foundation.css')) {
  // Insert AFTER `@import "tailwindcss";` (which is at the very top).
  const next = globals.replace(/(@import "tailwindcss";\s*\n)/, `$1${importLine}`);
  if (next === globals) {
    actions.push({ kind: 'warn', path: 'globals.css', note: 'no @import "tailwindcss" line found; skipping import insert' });
  } else {
    if (!dry && !checkMode) writeFileSync(GLOBALS_PATH, next, 'utf8');
    actions.push({ kind: 'patch', path: GLOBALS_PATH, note: 'inserted @import "./tincture/foundation.css"' });
  }
}

// 4. data-surface annotations on the SURFACE_PATCHES files
for (const patch of SURFACE_PATCHES) {
  if (!existsSync(patch.file)) {
    actions.push({ kind: 'skip', path: patch.note, note: 'file missing' });
    continue;
  }
  const before = readFileSync(patch.file, 'utf8');
  const { next, touched } = annotateDataSurface(before);
  if (touched === 0) continue;
  if (!dry && !checkMode) writeFileSync(patch.file, next, 'utf8');
  actions.push({ kind: 'annotate', path: patch.note, count: touched });
}

// ─── Report ────────────────────────────────────────────────────────────
console.log('tincture-init \u2014 Phase 0');
console.log('');
if (actions.length === 0) {
  console.log('no actions \u2014 already up-to-date.');
} else {
  for (const a of actions) {
    const label = `${a.kind.padEnd(8)} ${a.path}`;
    const extras = [a.count ? `count=${a.count}` : null, a.note ? `(${a.note})` : null].filter(Boolean).join(' ');
    console.log(`  ${label}  ${extras}`);
  }
}
console.log('');
console.log(`mode: ${dry ? 'dry-run' : checkMode ? 'check' : 'apply'}`);

if (checkMode) {
  // Anything that would have changed in apply mode = pending
  const pending = actions.filter((a) => ['create', 'update', 'patch', 'annotate'].includes(a.kind));
  if (pending.length > 0) {
    console.error(`\nx ${pending.length} action(s) pending.`);
    process.exit(1);
  }
  console.log('clean.');
  process.exit(0);
}
