// GENERATED by tincture/codegen-v2.mjs — do not edit by hand.
// Registry: tincture/v0.2-example v0.2.0-alpha

/** Union of every token ID in the registry. */
export type TokenId = "accent" | "accent-fg" | "bg" | "brand-mark-primary" | "brand-mark-secondary" | "ink" | "ink-soft" | "leading-tight" | "motion-snap" | "radius-pill" | "radius-soft" | "shadow-lifted" | "space-rhythm" | "space-section" | "track-display" | "weight-body" | "weight-display";

/** All token IDs as a tuple (use `as const` for inference). */
export const TOKEN_IDS = ["accent", "accent-fg", "bg", "brand-mark-primary", "brand-mark-secondary", "ink", "ink-soft", "leading-tight", "motion-snap", "radius-pill", "radius-soft", "shadow-lifted", "space-rhythm", "space-section", "track-display", "weight-body", "weight-display"] as const;
